# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Drivertools

TLV_TYPE_TDL_PCLIENT    = TLV_META_TYPE_RAW    | (TLV_EXTENSIONS + 1333)
TLV_TYPE_TDL_ERROR_MSG 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 1336)
TLV_TYPE_TDL_INJECT     = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 1337)
TLV_TYPE_TDL_DO_NOTHING = 	 TLV_META_TYPE_RAW | (TLV_EXTENSIONS + 1339)

# TLV_TYPE_DEV_IMAGE = TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 911)
# TLV_TYPE_DEV_AUDIO = TLV_META_TYPE_STRING| (TLV_EXTENSIONS + 912)
# TLV_TYPE_DEV_SCREEN = TLV_META_TYPE_RAW| (TLV_EXTENSIONS + 913)
# TLV_TYPE_DEV_RECTIME = TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 914)

end
end
end
end
end
